<div>
    <p class="text-sm font-extrabold uppercase tracking-[0.18em] text-indigo-600">Content quality</p>
    <h1 class="mt-2 text-4xl font-extrabold">Surse și raportări</h1>

    <div class="mt-8 grid gap-8 xl:grid-cols-3">
        <section><h2 class="text-xl font-extrabold">Raportări deschise</h2><div class="mt-4 space-y-3">@forelse($reports as $report)<article class="rounded-2xl border border-slate-200 bg-white p-5 dark:border-white/10 dark:bg-white/5"><p class="text-xs font-bold uppercase text-amber-600">{{ $report->reason }}</p><p class="mt-2 text-sm font-semibold">{{ Str::limit($report->question?->prompt ?? 'Întrebare ștearsă', 150) }}</p>@if($report->message)<p class="mt-2 text-sm text-slate-500">{{ $report->message }}</p>@endif<p class="mt-2 text-xs text-slate-400">{{ $report->user->email }}</p><button wire:click="resolveReport({{ $report->id }})" class="mt-4 rounded-xl bg-slate-950 px-3 py-2 text-sm font-bold text-white dark:bg-white dark:text-slate-950">Rezolvat</button></article>@empty<p class="text-slate-500">Nicio raportare deschisă.</p>@endforelse</div></section>
        <section><h2 class="text-xl font-extrabold">Surse expirate &gt; 6 luni</h2><div class="mt-4 space-y-3">@forelse($staleQuestions as $question)<article class="rounded-2xl border border-slate-200 bg-white p-5 dark:border-white/10 dark:bg-white/5"><p class="text-xs text-slate-500">{{ $question->vertical->name }} · verificat {{ $question->source_checked_at?->format('d.m.Y') ?? 'niciodată' }}</p><p class="mt-2 text-sm font-semibold">{{ Str::limit($question->prompt, 150) }}</p><a href="{{ $question->source_url }}" target="_blank" rel="noopener" class="mt-3 block text-sm font-bold text-indigo-600">Deschide sursa ↗</a><button wire:click="verifySource({{ $question->id }})" class="mt-3 rounded-xl border px-3 py-2 text-sm font-bold dark:border-white/15">Sursă verificată azi</button></article>@empty<p class="text-slate-500">Nicio sursă expirată.</p>@endforelse</div></section>
        <section><h2 class="text-xl font-extrabold">Fără sursă</h2><div class="mt-4 space-y-3">@forelse($missingSources as $question)<article class="rounded-2xl border border-slate-200 bg-white p-5 dark:border-white/10 dark:bg-white/5"><p class="text-xs text-slate-500">{{ $question->vertical->name }} · #{{ $question->id }}</p><p class="mt-2 text-sm font-semibold">{{ Str::limit($question->prompt, 150) }}</p></article>@empty<p class="text-slate-500">Toate întrebările au sursă.</p>@endforelse</div></section>
    </div>
</div>
